name: Release Version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: notifications

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Pack Domain Library
        run: npm pack ./libs/domain

      - name: Rename Package
        run: mv bank_domain-1.0.0.tgz bank_domain_viveros.tgz

      # This step creates the GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: bank_domain_viveros.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
